import React, { createContext, useState, useContext } from 'react';

// Translation dictionary
const translations = {
  en: {
    createWorkspace: 'Create Workspace',
    ofspace: 'OFSPACE.CO',
    dashboard: 'Dashboard',
    sales: 'Sales',
    revenue: 'Revenue',
    customers: 'Customers',
    performance: 'Performance',
    chartLabel: 'Monthly Sales',
    settings: 'Settings',
    profile: 'Profile',
    logout: 'Logout',
    welcome: 'Welcome back,',
    selectLanguage: 'Language',
    login: 'Login',
    addYourItems: 'Add your Items',
    cancel: 'Cancel',
    add: 'Add',
    overview: 'Overview',
    lastUpdated: 'Last updated:',
    totalItems: 'Total Items',
    totalValue: 'Total Value',
    averagePrice: 'Average Price',
    achievementBadges: 'Achievement Badges',
    bronzeTier: 'Bronze Tier',
    silverTier: 'Silver Tier',
    goldTier: 'Gold Tier',
    itemsAdded: 'item(s) added',
    nextMilestone: '🚀 {count} more to reach Silver!',
    addFirstItemBadge: 'Add your first item to earn a badge 🏆',
    viewAllItems: 'View all items →',
    allItems: 'All Items',
    yourItems: 'Your Items',
    byName: 'By Name',
    byPrice: 'By Price',
    noItemsYet: 'No items yet. Click',
    createWorkspaceLink: '+ createWorkspace',
    toAddFirst: 'to add your first item.',
    analytics: 'Analytics',
    priceOverview: 'Price Overview',
    priceRange: 'Price Range',
    items: 'items',
    item: 'item',
    itemsCount: '{count} item(s)',
    barPercent: 'Bars show % in each price range',
    monthlyDistribution: 'Monthly Distribution',
    activityCalendar: 'Activity Calendar',
    noActivity: 'No activity',
    itemAdded: 'Item added',
    todayIs: 'Today is',
  },
  'en-US': {
    // Same as en
    createWorkspace: 'Create Workspace',
    ofspace: 'OFSPACE.CO',
    dashboard: 'Dashboard',
    sales: 'Sales',
    revenue: 'Revenue',
    customers: 'Customers',
    performance: 'Performance',
    chartLabel: 'Monthly Sales',
    settings: 'Settings',
    profile: 'Profile',
    logout: 'Logout',
    welcome: 'Welcome back,',
    selectLanguage: 'Language',
    login: 'Login',
    addYourItems: 'Add your Items',
    cancel: 'Cancel',
    add: 'Add',
    overview: 'Overview',
    lastUpdated: 'Last updated:',
    totalItems: 'Total Items',
    totalValue: 'Total Value',
    averagePrice: 'Average Price',
    achievementBadges: 'Achievement Badges',
    bronzeTier: 'Bronze Tier',
    silverTier: 'Silver Tier',
    goldTier: 'Gold Tier',
    itemsAdded: 'item(s) added',
    nextMilestone: '🚀 {count} more to reach Silver!',
    addFirstItemBadge: 'Add your first item to earn a badge 🏆',
    viewAllItems: 'View all items →',
    allItems: 'All Items',
    yourItems: 'Your Items',
    byName: 'By Name',
    byPrice: 'By Price',
    noItemsYet: 'No items yet. Click',
    createWorkspaceLink: '+ createWorkspace',
    toAddFirst: 'to add your first item.',
    analytics: 'Analytics',
    priceOverview: 'Price Overview',
    priceRange: 'Price Range',
    items: 'items',
    item: 'item',
    itemsCount: '{count} item(s)',
    barPercent: 'Bars show % in each price range',
    monthlyDistribution: 'Monthly Distribution',
    activityCalendar: 'Activity Calendar',
    noActivity: 'No activity',
    itemAdded: 'Item added',
    todayIs: 'Today is',
  },
  hi: {
    createWorkspace: 'कार्यक्षेत्र बनाएं',
    ofspace: 'OFSPACE.CO',
    dashboard: 'डैशबोर्ड',
    sales: 'बिक्री',
    revenue: 'राजस्व',
    customers: 'ग्राहक',
    performance: 'प्रदर्शन',
    chartLabel: 'मासिक बिक्री',
    settings: 'सेटिंग्स',
    profile: 'प्रोफाइल',
    logout: 'लॉग आउट',
    welcome: 'वापस आओ,',
    selectLanguage: 'भाषा',
    login: 'लॉग इन',
    addYourItems: 'अपनी वस्तुएँ जोड़ें',
    cancel: 'रद्द करें',
    add: 'जोड़ें',
    overview: 'अवलोकन',
    lastUpdated: 'अंतिम अद्यतन:',
    totalItems: 'कुल वस्तुएँ',
    totalValue: 'कुल मूल्य',
    averagePrice: 'औसत मूल्य',
    achievementBadges: 'उपलब्धि बैज',
    bronzeTier: 'कांस्य स्तर',
    silverTier: 'रजत स्तर',
    goldTier: 'स्वर्ण स्तर',
    itemsAdded: 'वस्तु(एँ) जोड़ी गईं',
    nextMilestone: '🚀 रजत तक पहुँचने के लिए {count} और!',
    addFirstItemBadge: 'बैज अर्जित करने के लिए पहली वस्तु जोड़ें 🏆',
    viewAllItems: 'सभी वस्तुएँ देखें →',
    allItems: 'सभी वस्तुएँ',
    yourItems: 'आपकी वस्तुएँ',
    byName: 'नाम से',
    byPrice: 'मूल्य से',
    noItemsYet: 'अभी तक कोई वस्तु नहीं।',
    createWorkspaceLink: '+ कार्यक्षेत्र बनाएं',
    toAddFirst: 'पहली वस्तु जोड़ने के लिए क्लिक करें।',
    analytics: 'एनालिटिक्स',
    priceOverview: 'मूल्य अवलोकन',
    priceRange: 'मूल्य सीमा',
    items: 'वस्तुएँ',
    item: 'वस्तु',
    itemsCount: '{count} वस्तु(एँ)',
    barPercent: 'बार हर मूल्य सीमा में % दिखाते हैं',
    monthlyDistribution: 'मासिक वितरण',
    activityCalendar: 'गतिविधि कैलेंडर',
    noActivity: 'कोई गतिविधि नहीं',
    itemAdded: 'वस्तु जोड़ी गई',
    todayIs: 'आज है',
  },
  zh: {
    createWorkspace: '创建工作区',
    ofspace: 'OFSPACE.CO',
    dashboard: '仪表板',
    sales: '销售',
    revenue: '收入',
    customers: '客户',
    performance: '表现',
    chartLabel: '每月销售',
    settings: '设置',
    profile: '个人资料',
    logout: '登出',
    welcome: '欢迎回来，',
    selectLanguage: '语言',
    login: '登录',
    addYourItems: '添加您的物品',
    cancel: '取消',
    add: '添加',
    overview: '概述',
    lastUpdated: '最后更新：',
    totalItems: '物品总数',
    totalValue: '总价值',
    averagePrice: '平均价格',
    achievementBadges: '成就徽章',
    bronzeTier: '青铜等级',
    silverTier: '白银等级',
    goldTier: '黄金等级',
    itemsAdded: '已添加物品',
    nextMilestone: '🚀 再添加 {count} 个即可达到白银！',
    addFirstItemBadge: '添加您的第一个物品以赢得徽章 🏆',
    viewAllItems: '查看所有物品 →',
    allItems: '所有物品',
    yourItems: '您的物品',
    byName: '按名称',
    byPrice: '按价格',
    noItemsYet: '还没有物品。点击',
    createWorkspaceLink: '+ 创建工作区',
    toAddFirst: '添加您的第一个物品。',
    analytics: '分析',
    priceOverview: '价格概览',
    priceRange: '价格范围',
    items: '物品',
    item: '物品',
    itemsCount: '{count} 个物品',
    barPercent: '条形显示每个价格范围内的百分比',
    monthlyDistribution: '月度分布',
    activityCalendar: '活动日历',
    noActivity: '无活动',
    itemAdded: '物品已添加',
    todayIs: '今天是',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key, params = {}) => {
    let text = translations[language][key] || key;
    // Replace placeholders like {count}
    Object.keys(params).forEach(param => {
      text = text.replace(`{${param}}`, params[param]);
    });
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};